### ISSUE TITLE
CRAM supported?

### ISSUE THREAD

**Issue by ms-gx** [dayzerodx/counterr#2]
Thx for this tool!
Does it also support CRAM format?
If yes, how?

**Comment by jaekor91** [comment]
@ms-gx Thank you for using the tool! Currently, counterr does not support CRAM but it might be a quick extension to implement. I don't work with CRAM files usually so I don't have test files that I could use. Could you send me a CRAM file and its associated assembly so that I can implement and test CRAM support?

**Comment by ms-gx** [comment]
I can do that. Where do I upload it to? Send me the instructions to michael.schmid@genexa.ch
